.TH "/Users/andre/Documents/Xcode/Command Line Utility/Foundation/setversion/setversion.m" 3 "7 Jul 2009" "Version 0.1" "setversion" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/andre/Documents/Xcode/Command Line Utility/Foundation/setversion/setversion.m \- 
.SH SYNOPSIS
.br
.PP
\fC#import 'setversion.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBDAYZERO\fP   183"
.br
.ti -1c
.RI "#define \fBDAYNOW\fP   [[NSCalendarDate calendarDate] dayOfYear]"
.br
.ti -1c
.RI "#define \fBSV_VERSION\fP   (double)((DAYNOW-DAYZERO) * 1000) / 100000"
.br
.ti -1c
.RI "#define \fBSV_COMPILEDATE\fP"
.br
.ti -1c
.RI "#define \fBSV_VERSION_CONST\fP   '0.1'"
.br
.ti -1c
.RI "#define \fBSV_NAME_CONST\fP   'setversion'"
.br
.ti -1c
.RI "#define \fBstrequal\fP(a, b)   (!strcmp((a),(b)))"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "const char * \fBprogname\fP (void)"
.br
.ti -1c
.RI "void \fBprintUsage\fP (FILE *filedesc)"
.br
.ti -1c
.RI "void \fBprintVersion\fP (FILE *filedesc)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, const char *argv[])"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define DAYNOW   [[NSCalendarDate calendarDate] dayOfYear]"
.PP
.SS "#define DAYZERO   183"
.PP
.SS "#define strequal(a, b)   (!strcmp((a),(b)))"
.PP
.SS "#define SV_COMPILEDATE"
.PP
\fBValue:\fP
.PP
.nf
[[[NSCalendarDate calendarDate] descriptionWithCalendarFormat:@'%Y%m%d']\
                            cStringUsingEncoding:NSASCIIStringEncoding]
.fi
.SS "#define SV_NAME_CONST   'setversion'"
.PP
.SS "#define SV_VERSION   (double)((DAYNOW-DAYZERO) * 1000) / 100000"
.PP
.SS "#define SV_VERSION_CONST   '0.1'"
.PP
.SH "Function Documentation"
.PP 
.SS "int main (int argc, const char * argv[])"
.PP
.SS "void printUsage (FILE * filedesc)"
.PP
printUsage  Shows program usage  Prints a precomposed and hardwired function internal const string to the file descriptor supplied by user. 
.PP
\fBParameters:\fP
.RS 4
\fIfiledesc\fP the file descriptor to write to 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "void printVersion (FILE * filedesc)"
.PP
printVersion  Shows program version  Prints a precomposed and hardwired function internal const string to the file descriptor supplied by user. 
.PP
\fBParameters:\fP
.RS 4
\fIfiledesc\fP the file descriptor to write to 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "const char* progname (void)"
.PP
progname  Returns a program name based on the file name of the source file 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP description 
.RE
.PP
\fBReturns:\fP
.RS 4
String with program name 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for setversion from the source code.
